version: "3.9"
services:
  mask_apply:
    build: { context: ., dockerfile: docker/Dockerfile.kedro }
    environment:
      PIPELINE: mask_merge
      KEDRO_ENV: base
    volumes:
      - ./data:/project/data
      - ./conf:/project/conf:ro
      - ./src:/project/src:ro

  split:
    build: { context: ., dockerfile: docker/Dockerfile.kedro }
    environment:
      PIPELINE: data_split
      KEDRO_ENV: base
    depends_on: [mask_apply]
    volumes:
      - ./data:/project/data
      - ./conf:/project/conf:ro
      - ./src:/project/src:ro

  train:
    build: { context: ., dockerfile: docker/Dockerfile.train }
    environment:
      PIPELINE: training
      KEDRO_ENV: base
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: --gpus=all   # for older Docker; on newer: use  on run
    depends_on: [split]
    volumes:
      - ./data:/project/data
      - ./conf:/project/conf:ro
      - ./src:/project/src:ro

  ui:
    build: { context: ., dockerfile: docker/Dockerfile.kedro }
    environment:
      PIPELINE: ui
      MODEL_PATH: /project/data/06_models/model.h5
    ports: ["8000:8000"]
    depends_on: [train]
    volumes:
      - ./data:/project/data
      - ./conf:/project/conf:ro
      - ./src:/project/src:ro
