apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ui-hpa
  namespace: default   # change if you’re not in default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui   # must match your Deployment.metadata.name
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50   # scale if CPU > 50%
