gdrive_file_id: "12Q0V4JzWf9o5L6szJmmvXaCGSGQ5hy8z"
raw_data_dir: "data/01_raw/plantdisease"

raw_images_path: "data/01_raw/plantdisease/PlantVillage" 
intermediate_masks_path: "data/02_intermediate/maskingv5"
